# Tubes PRD
print("Selamat datang di aplikasi Traveller. Berapa lama Anda akan menjelajahi Bandung?")
hari = input()
print("\n")
print("Kami menyarankan agar setiap hari hanya diisi 8-10 jam aktivitas untuk mengantisipasi kejadian tak terduga dan mengakomodasi waktu perjalanan")
print("Silahkan memilih kategori aktivitas kegiatan yang ingin dilakukan: ")
print("Kegiatan air")
print("Wisata Alam")
print("Museum")
print("Spot Foto")
print("Kuliner")
print("Anak anak")
print("Trekking")
print("Panjat Tebing")
